id: AD6B66D3F
title: 'Treasury of Supreme Blessings: A Guru Yoga'
type: translation
pechas:
- I16800A96
- IC86C58BE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:58.691831
  last_modified_at: 2023-01-04 12:32:58.691840
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I16800A96/89F9: 81C6
  IC86C58BE/A3E0: 81C6
